config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # resources :christmastrees
  resources :christmastrees do
    resources :bookings, only: [ :new, :create ]
    # resources :reviews, only: [ :new, :create ]
  end

  resources :bookings do
    member do
      post :approve
    end
    member do
      post :decline
    end
  end
  resources :users, only: [:show]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :christmastree

  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :christmastree, presence: true

end

app/models/christmastree.rb
class Christmastree < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  validates :name, presence: true
  validates :price, presence: true
  validates :height, presence: true
  validates :plant_type, presence: true
  has_many_attached :photos
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :christmastrees
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?
  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
before_action :set_booking, only: [ :show ]
before_action :set_christmastree, only: [ :new, :create ]

  def index
    @bookings = current_user.bookings
  end

  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.christmastree = Christmastree.find(params[:christmastree_id])
    if @booking.save
      redirect_to booking_path(@booking)
    else
      redirect_to christmastree_path(@christmastree)
    end
  end

  def destroy

    @booking = Booking.find(params[:id])
    @booking.destroy
    redirect_to users_show_path, status: :see_other
  end

  def approve
    @booking = Booking.find(params[:id])
    @booking.update(status: "approved")
    if @booking.status == "approved"
      @booking.update(approval: true)
      redirect_to user_path(@booking.christmastree.user)
    end
  end

  def decline
    @booking = Booking.find(params[:id])
    @booking.update(status: "declined")
    if @booking.status == "declined"
      @booking.update(approval: false)
      redirect_to user_path(@booking.christmastree.user)
    end
  end

# def num_of_days
#   @booking = Booking.find(params[:id])
#   end_date = params[:end_date].value
#   start_date = params[:start_date].value
#   (@booking.start_date..@booking.end_date).count
# end

private

  def set_booking
    @booking = Booking.find(params[:id])
  end

  def set_christmastree

    @christmastree = Christmastree.find(params[:christmastree_id])
  end

def booking_params
  params.require(:booking).permit(:user_id, :price, :start_date, :end_date)
end
end

app/controllers/christmastrees_controller.rb
class ChristmastreesController < ApplicationController
  def index
    @christmastrees = Christmastree.all
    @markers = @christmastrees.geocoded.map do |tree|
      {
        lat: tree.latitude,
        lng: tree.longitude,
        image_url: helpers.asset_url("christmas_tree_icon.png")
      }
    end
  end

  def show
    @christmastree = Christmastree.find(params[:id])
    @booking = Booking.new
  end

  def new
    @christmastree = Christmastree.new
  end

  def create
    @christmastree = Christmastree.new(christmastree_params)
    @christmastree.user = current_user
    if @christmastree.save
      redirect_to christmastree_path(@christmastree)
    else
      render :new, status: :unprocessable_entity
    end
  end


  def edit
    @christmastree = Christmastree.find(params[:id])
  end

  def update
    @christmastree = Christmastree.find(params[:id])
    if @christmastree.update(christmastree_params)
      redirect_to christmastree_path(@christmastree)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @christmastree = Christmastree.find(params[:id])
    @christmastree.destroy
    redirect_to users_show_path, status: :see_other
  end

  private

  def christmastree_params
    params.require(:christmastree).permit(:description, :price, :height, :plant_type, :name, :user_id, :address, photos: [])
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    # user = User.find(params[:id])
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/index.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>
<%= current_user.username %>
<% @bookings.each do |booking| %>
  <%= booking.christmastree.name  %>
  <%#= link_to "delete", booking_path(booking), data: { turbo_method: :delete } %>
  <%= link_to "Delete", booking_path(booking), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'}, class:"btn btn-success" %>
    <% end %>

app/views/bookings/new.html.erb
<%# <div class="confirmation-box col-md-4">
  <div class="listing-price">
    <div class="form-group"> %>
      <%# <h4><%= @christmastree.price %>
      <%# <p>per day plus service fees</p><br> %>

      <%= simple_form_for [@christmastree, @booking] do |f| %>
        <%= f.input :start_date, as: :date, required: false, input_html: {class: "datepicker"} %>
        <%= f.input :end_date, as: :date, required: false, input_html: {class: "datepicker"} %>
        <%= f.button :submit %>
      <%end%>

        <%# <h5>Subtotal: <strong>$<%= @christmastree.price %>



        <%# <br><br>
        <p class="text-center" style="color: grey">You won't be charged yet</p>
        <%# <p class="text-center" style="color: grey">-- Or --</p> %>

        <%# <button class="btn btn-primary custom-link form-control"><%= link_to "Contact owner", conversations_path</button> %>
      <%# <% end %>
<%# #     </div>
#   </div>
# </div> %>

app/views/bookings/show.html.erb
<div class="container">
  <div class="container-listing">
  <br>



  <h4>Congratulations, for your booking request, nice choice! Now just wait for <%= @booking.christmastree.user.username %> to accept or decline your request, it shouldn't take too long!</h4>
  <h4><strong>Reminder of your request : </strong></h4>
  <h4><strong><%= @booking.christmastree.name %></strong> for <strong><%=(@booking.start_date..@booking.end_date).count %> days</strong>, starting <strong><%= @booking.start_date.strftime('%A %d %B') %></strong>, from <strong><%= @booking.christmastree.user.username %></strong>, at the price of <strong> €<%=(@booking.start_date..@booking.end_date).count * @booking.christmastree.price %>!</strong></h4>



  </div>
  <br>
   <h4><%= link_to "back to trees", christmastrees_path, class: "btn btn-success" %> </h4>
</div>

app/views/christmastrees/edit.html.erb
<div class="container ">
<%= simple_form_for (@christmastree) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :height %>
  <%= f.input :description %>
  <%= f.input :price, label: 'Price per day in €' %>
  <%= f.input :plant_type, :collection => ['Balsam Fir','Fraser Fir','Canaan Fir','Douglas Fir','Grand Fir', 'Noble Fir', 'Concolor Fir', 'White Pine', 'Scotch Pine', 'Virginia Pine', 'Blue Spruce', 'Norway Spruce', 'White Spruce', 'Arizona Cypress', 'Leyland Cypress', 'Red Cedar'] %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit 'Edit tree', class: "btn btn-success"%>
<% end %>
</div>

app/views/christmastrees/index.html.erb
<div class="container ">

  <h3 Christmas trees available></h3>
    <div class="container">
      <div class="row justify-content-center" data-controller="map">
        <div class="col-6">
          <form class="d-flex my-5" id="form" data-action="submit->map#search">
            <input type="text" id="address" class="form-control flex-grow-1 me-2" placeholder="Type an address" data-map-target="form">
            <input type="submit" value="Search!" class="btn btn-success" >
          </form>
        </div>
      </div>
    </div>
<br>

    <div style="width: 100%; height: 600px;"
      data-controller="map"
      data-map-markers-value="<%= @markers.to_json %>"
      data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
    </div>

       <% @christmastrees.each do |tree| %>
         <div class="d-inline-flex p-2 m-5">
          <div class="card" style="width: 18rem;">

            <%= link_to christmastree_path(tree) do %>
            <% if tree.photos.attached? %>
                <%= cl_image_tag tree.photos.first.key, crop: :fill, class: "card-img-top", alt: "Card image cap"  %>
            <% else %>
                <img class="card-img-top" src="https://images.costco-static.com/ImageDelivery/imageService?profileId=12026540&imageId=2006176-847__1&recipeName=350" alt="Card image cap">
            <% end %>
                <div class="card-body">
                  <p class="card-title"><%= tree.name %></p>
                  <div class="d-flex justify-content-between">
                    <p><%= tree.address %></p>
                    <p><%= tree.price %>€ per day</p>
                  </div>
                </div>
            <% end %>
          </div>
         </div>
        <% end %>
</div>

app/views/christmastrees/new.html.erb
<div class="container">
<%= simple_form_for (@christmastree) do |f| %>
  <%= f.input :name %>
  <%= f.input :address %>
  <%= f.input :height %>
  <%= f.input :description %>
  <%= f.input :price, label: 'Price per day in €' %>
  <%= f.input :plant_type, :collection => ['Balsam Fir','Fraser Fir','Canaan Fir','Douglas Fir','Grand Fir', 'Noble Fir', 'Concolor Fir', 'White Pine', 'Scotch Pine', 'Virginia Pine', 'Blue Spruce', 'Norway Spruce', 'White Spruce', 'Arizona Cypress', 'Leyland Cypress', 'Red Cedar'] %>
  <%= f.input :photos, as: :file, input_html: { multiple: true } %>
  <%= f.submit 'Create tree', class: "btn btn-success"%>
<% end %>
</div>

app/views/christmastrees/show.html.erb
<div class="container" >
  <div class="row">
    <% @christmastree.photos.each do |photo| %>
      <div class="col-lg-4 col-md-12 mb-4 mb-lg-0">
      <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill, class: "w-100 shadow-1-strong rounded mb-4"  %>
      </div>
    <% end %>
  </div>

  <div class="tree-info">
    <div class="w-50" id="treeinfo">
      <h1><%= @christmastree.name %></h1>
      <h5><strong>€<%= @christmastree.price %> per day</strong></h5>
     <p><%= @christmastree.height %> cm high | Type: <%= @christmastree.plant_type %> | Owner: <%= @christmastree.user.username %> | Location: <%= @christmastree.address %>
     </p>
        <hr>
     <p> <%= @christmastree.description %></p>
        <%#= link_to "Book this tree!", new_christmastree_booking_path(@christmastree) %>
    </div>
    <div data-controller="price">
       <%# <h3>BOOK THIS TREE</h3> %>
          <div class=" p-5 rounded shadow-sm p-3 mb-5 rounded" style="background-color: beige">
          <h5><strong>€<%= @christmastree.price %> per day</strong></h5>
           <%= simple_form_for [@christmastree, @booking], data: { controller: 'flatpickr' } do |f| %>
           <%= f.input :start_date, as: :string, input_html: { data: { flatpickr_target: "startDate", price_target: "start" } } %>
           <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endDate", price_target: "end", action: "input->price#add"} } %>
           <%#= f.input :start_date, as: :date, required: false, input_html: {class: "datepicker"} %>
           <%#= f.input :end_date, as: :date, required: false, input_html: {class: "datepicker"} %>
          <%= f.submit 'Book', class: "btn btn-default btn-success", data: { confirm: "Are you sure you want to submit this form?" }%>
          <%end%>

         </div>
    <div>
  </div>
  </div>
  </div>
  <hr>

  <h4><%= link_to "back to all trees", christmastrees_path, class: "btn btn-success" %> </h4>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbntrees</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <style>
      body {
        background-image: linear-gradient(rgba(255,255,255,0.3), rgba(255,255,255,0.3)), url("https://cdn.windowsreport.com/wp-content/uploads/2019/12/Christmas-886x590.jpg");
        background-repeat: no-repeat;
        background-attachment: fixed;
        background-size: cover;
      }
    </style>
  </head>

  <body>
    <%# <div style="background-image: url('https://www.website.com/images/image_background.jpg');"> %>
    <% if params[:controller] != 'pages' && params[:action] != 'home' %>
      <%= render "shared/navbar" %>
    <% end %>
      <div class="wrapper">
    <%= render "shared/flashes" %>
    <%= yield %>
      <div>
        <% if params[:controller] != 'pages' && params[:action] != 'home' %>
          <%= render "shared/footer" %>
        <% end %>
      </div>
    <%# </div> %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>

</html>

app/views/pages/home.html.erb
<div id="snow" data-controller="snow"></div>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.4)), url(https://cdn.windowsreport.com/wp-content/uploads/2019/12/Christmas-886x590.jpg);">
  <div class="container">
    <h1>AirBnTrees</h1>
    <p>This Christmas, rent the tree, keep the spirit</p>
    <%= link_to "Browse trees", christmastrees_path, class: "btn btn-success" %>
  </div>
</div>
<%# https://www.prairiegardens.com/wp-content/uploads/2018/11/2014_FORESTOFTREES-Feature-.jpg %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
        <% if user_signed_in? %>
      <h4> <%= current_user.username %> <i class="fa-solid fa-tree"></i></i></h4>
    <% end %>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to christmastrees_path, class: "navbar-brand" do %>
      <div class="d-flex align-items-center justify-content-between">
        <h4>
        <i class="fa-solid fa-tree"></i>
        AirBnTrees</h4>
      </div>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "My trees and bookings", users_show_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Publish an offer", new_christmastree_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://image.shutterstock.com/image-vector/thin-line-user-icon-on-260nw-519039097.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My trees and bookings", users_show_path, class: "dropdown-item" %>
              <%= link_to "Publish an offer", new_christmastree_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<div class=container mt-5>

<h3>Christmas trees available</h3>
<br>
  <% @christmastrees.each do |tree| %>

<div class="card-product mt-5">
 <img src="https://images.costco-static.com/ImageDelivery/imageService?profileId=12026540&imageId=2006176-847__1&recipeName=350" />
      <p><%= link_to tree.name, christmastree_path(tree), class: "card-product-infos" %></p>

  </div>
  <% end %>
</div>

app/views/users/show.html.erb
<div class="container mt-5">
  <br>
  <h2>Hi, <%= @user.username %>!</h2>
  <br>

    <div class="container">
      <div class="row">

        <div class="col-sm">
          <h3>My trees</h3>
         <% @user.christmastrees.each do |tree| %>
              <div class="card mb-2" style="width: 18rem;">
                 <div class="card-body d-flex justify-content-between">
                  <div>
                    <h5 class="card-title"><%= tree.name %></h5>
                  </div>
                    <div>
                      <%= link_to christmastree_path(tree), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} do %>
                        <i class="fa-solid fa-trash-can"></i>
                      <% end %>
                      <%= link_to edit_christmastree_path(tree) do %>
                        <i class="fa-solid fa-pen"></i>
                      <% end %>
                    </div>
                 </div>
              </div>
              <% end %>
           </div>

        <div class="col-sm">
          <h3>My bookings</h3>
        <% @user.bookings.each do |booking| %>
          <div class="card mb-2" style="width: 18rem;">
             <div class="card-body">
               <h5 class="card-title"><%= booking.christmastree.name %></h5>
               <p class="card-text"> <%= booking.start_date.strftime('%A %d %B') %> to <%= booking.end_date.strftime('%A %d %B') %></p>
               <% if booking.status == "declined" %>
               <p> Your booking has been rejected</p>
               <% elsif booking.approval == false %>
               <p> YYour booking is pending</p>
               <% else %>
               <p> Your booking has been approved!</p>
               <% end %>
              <%= link_to booking_path(booking), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} do %>
                <i class="fa-solid fa-trash-can"></i>
              <% end %>
              </div>
            </div>
               <% end %>
          </div>

        <div class="col-sm">
          <h3>My booking requests</h3>
          <% @user.christmastrees.each do |tree| %>
          <% tree.bookings.each do |booking| %>
          <div class="card mb-2" style="width: 18rem;">
             <div class="card-body">
              <h5 class="card-title"><%= booking.user.username %> has booked your tree '<%= booking.christmastree.name %>'</h5>
              <p class="card-text"> <%= booking.start_date.strftime('%A %d %B') %> to <%= booking.end_date.strftime('%A %d %B') %></p>
              <% if booking.status.nil? %>
                  <%= button_to approve_booking_path(booking), method: :post, class: "button" do %>
                    <i class="fa-solid fa-check"></i>
                  <% end %>
                  <%= button_to decline_booking_path(booking), method: :post, class: "button" do  %>
                    <i class="fa-solid fa-xmark"></i>
                  <% end %>
              <% elsif booking.status == "approved" %>
                <p> You have approved <%= booking.user.username %> request</p>
              <% elsif booking.status == "declined" %>
                <p> You have declined <%= booking.user.username %> request</p>
              <% end %>

              <%= link_to booking_path(booking), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} do %>
                <i class="fa-solid fa-trash-can"></i>
              <% end %>
            </div>
          </div>
          <% end %>
          <% end %>
        </div>
      </div>
    </div>
<hr>
  <%= link_to "back to christmas trees", christmastrees_path, class: "btn btn-success"%>
</div>